# Generated by Django 5.0.4 on 2024-04-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_likedposts_liked_post_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_img',
            field=models.ImageField(blank=True, upload_to='comment_images'),
        ),
    ]
