# Generated by Django 3.2.23 on 2024-04-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, default='example@maine.edu', max_length=254, unique=True),
        ),
    ]
