# Generated by Django 5.0.4 on 2024-04-19 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_comments_rename_likepost_likedposts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FollowersCount',
            new_name='Followers',
        ),
    ]
