# Generated by Django 5.0.4 on 2024-04-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_post_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked',
        ),
        migrations.AddField(
            model_name='likedposts',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
